export const GAME_TABLE_STATE_POLL_MS = 10_000
export const GAME_BALANCE_POLL_MS = 8_000
export const FAIRNESS_ARTIFACT_POLL_MS = 2_500
export const ROULETTE_MAX_BET_SPOTS = 8
export const BACCARAT_MAX_SHOE_DRAW_ATTEMPTS = 32
